### ISSUE TITLE
running test.db problem

### ISSUE THREAD

**Issue by forestmojo** [mdavidsaver/pyDevSup#23]
hi, mdavidsaver:

I try to run the example in testApp, like "../bin/linux-x86_64/softIocPy2.7 -d test.db". the output like following:
Bad character '$' in record name "$(P)li:cnt"
Bad character '$' in record name "$(P)val:a"
Bad character '$' in record name "$(P)val:b"
Bad character '$' in record name "$(P)wf"
Bad character '$' in record name "$(P)async:cnt"
Bad character '$' in record name "$(P):A-SP"
Bad character '$' in record name "$(P):B-SP"
Bad character '$' in record name "$(P):A-RB"
Bad character '$' in record name "$(P)li:time"
Starting iocInit
############################################################################
############################################################################
/usr/lib64/python2.7/site-packages/scipy/__init__.py:115: UserWarning: Numpy 1.8.2 or above is recommended for this version of scipy (detected version 1.7.1)
  UserWarning)
start <test3.WfSup object at 0x7effa3efe210>
test1 build for $(P)li:cnt
Record("$(P)li:cnt") (5, 4, 1)
VAL 0
$(P)val:a: Exception in add_record
Traceback (most recent call last):
  File "/home/geyang/tmp/pyDevSup-master/python2.7/linux-x86_64/devsup/db.py", line 416, in processLink
    return rec, mod.build(rec, args)
  File "/home/geyang/tmp/pyDevSup-master/testApp/test2.py", line 37, in __init__
    self.driver, self.record = insts[args], rec
KeyError: 'AAAA'
$(P)val:b: Exception in add_record
Traceback (most recent call last):
  File "/home/geyang/tmp/pyDevSup-master/python2.7/linux-x86_64/devsup/db.py", line 416, in processLink
    return rec, mod.build(rec, args)
  File "/home/geyang/tmp/pyDevSup-master/testApp/test2.py", line 37, in __init__
    self.driver, self.record = insts[args], rec
KeyError: 'AAAA'
PV: $(P)val:a scanAdd: I/O Intr not valid

PV: $(P)val:b scanAdd: I/O Intr not valid

iocRun: All initialization complete
epics> 

my question is:
1. how to implement marco $P?
2.pyDevSup does not support I/O Intr, why you set this in db?
3.what's the meaning of "AAAA", is it arg for py file input?
How to solve these erros? thanks a lot.

**Comment by mdavidsaver** [comment]
Add an argument "-m P=XYZ" before the "-d" to provide macro definitions.

bin/linux-x86_64/softIocPy2.7 -m P=XYZ -d test.db

**Comment by forestmojo** [comment]
thanks a lot. If I want to try weatherApp, how to define marco LOC's value?
