### ISSUE TITLE
Trying to run an ioc that used pyDevSup as a separate module

### ISSUE THREAD

**Issue by iarriagada** [mdavidsaver/pyDevSup#24]
Hello David, 
I'm trying to run an IOC as a separate module from but so far, I can get the Python Device to work.

I'm currently running **EPICS R3.14.12.5**
**Python3.5**
**numpy1.12.0**

here's the output when I try to run the IOC
```#!../../bin/linux-x86_64/pydevEx
## You may have to change pydevEx to something else
## everywhere it appears in this file
< envPaths
epicsEnvSet("ARCH","linux-x86_64")
epicsEnvSet("IOC","iocpydevEx")
epicsEnvSet("TOP","/home/iarriagada/work/ioc/pydevEx")
epicsEnvSet("PYDEVSUP","/home/iarriagada/work/support/pyDevSup")
epicsEnvSet("EPICS_BASE","/gemsoft/opt/epics/base")
cd /home/iarriagada/work/ioc/pydevEx
## Register all support components
dbLoadDatabase "dbd/pydevEx.dbd"
pydevEx_registerRecordDeviceDriver pdbbase
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/iarriagada/work/support/pyDevSup/python3.5m/linux-x86_64/devsup/__init__.py", line 5, in <module>
    from . import _dbapi
ImportError: /home/iarriagada/work/support/pyDevSup/python3.5m/linux-x86_64/devsup/_dbapi.so: undefined symbol: iocBuildIsolated
## Load record instances
#dbLoadTemplate "db/userHost.substitutions"
dbLoadRecords "db/pydevexTop.db", "user=iarriagadaHost"
Can't set "test:count.DTYP" to "Python Device"
Error at or before ")" in file "db/pydevexTop.db" line 2
## Set this to see messages from mySub
#var mySubDebug 1
## Run this to trace the stages of iocInit
#traceIocInit
cd /home/iarriagada/work/ioc/pydevEx/iocBoot/iocpydevEx
iocInit
Starting iocInit
############################################################################
## EPICS R3.14.12 $Date: Wed 2010-11-24 14:50:38 -0600$
## EPICS Base built Jan 30 2017
############################################################################
iocRun: All initialization complete
## Start any sequence programs
#seq sncExample, "user=iarriagadaHost"
epics>
```
When I compile pyDevSup, I get the following message
```
/usr/bin/gcc -c  -D_POSIX_C_SOURCE=199506L -D_POSIX_THREADS -D_XOPEN_SOURCE=500        -DXEPICS_ARCH=\"linux-x86_64\" -DXPYDEV_BASE=\"/home/iarriagada/work/support/pyDevSup\" -DXEPICS_BASE=\"/gemsoft/opt/epics/base\" -DPYDIR=\"python3.5\" -DHAVE_NUMPY  -DUSE_TYPED_RSET  -D_X86_64_  -DUNIX  -D_BSD_SOURCE -Dlinux  -D_REENTRANT   -O3   -Wall    -Wno-unused-result -Wsign-compare   -m64     -g -fPIC -MMD -I. -I../O.Common -I. -I.. -I../../../include/os/Linux -I../../../include -I/gemsoft/opt/epics/base/include/os/Linux -I/gemsoft/opt/epics/base/include       -I/usr/lib64/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m ../dbapi.c 
In file included from /usr/lib64/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                 from /usr/lib64/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from ../dbapi.c:7:
/usr/lib64/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
../dbapi.c: In function ‘py_iocInit’:
../dbapi.c:243:9: warning: implicit declaration of function ‘iocBuildIsolated’ [-Wimplicit-function-declaration]
         ret = isolate ? iocBuildIsolated() : iocBuild();
         ^
../dbapi.c: At top level:
../dbapi.c:287:1: warning: initialization from incompatible pointer type [enabled by default]
 };
 ^
../dbapi.c:287:1: warning: (near initialization for ‘dbapimodule.m_methods’) [enabled by default]
```

**Comment by mdavidsaver** [comment]
It looks like support for 3.14 is broken.  `iocBuildIsolated()` referenced in `devsupApp/src/dbapi.c` was added in 3.15.  It should be made conditional like the references to `dbUnitTest.h` in `devsupApp/src/utest.c`.

The fix isn't too difficult, but I have to ask.  Can you switch to Base >=3.15 ?  Support for 3.14 is more involved since the IOC integration code can't be covered by unittests until 3.15.

**Comment by mdavidsaver** [comment]
Should be fixed by 3620e1e0139a5d645b1db801ea32db52123fabbd please update and retest.

**Comment by iarriagada** [comment]
Ok, I will test shortly.
All our IOCs at the telescope are currently running R3.14, that is why I wanted to implement some features using this support package. We are in the process of moving over to R3.15 but it's a mid to long term goal at the moment.
I will try it with R3.15 in my dev machine as well.
Thank you for you time David!

**Comment by iarriagada** [comment]
Success! It works well now.
I will continue testing out the module.
Thank you David!
