### ISSUE TITLE
Record.setTime(datetime) Error

### ISSUE THREAD

**Issue by eltos** [mdavidsaver/pyDevSup#6]
When calling `setTime` on a record instance with a datetime object as parameter, the following exception is thrown:

```
Traceback (most recent call last):
  File "ioc/test.py", line 129, in get_value
    record.setTime(t)
  File "ioc/python3.4/linux-x86_64/devsup/db.py", line 262, in setTime
    super(Record, self).setTime(sec, nsec)
UnboundLocalError: local variable 'sec' referenced before assignment
```

**Comment by mdavidsaver** [comment]
Thanks for fixing this.
