### ISSUE TITLE
trying to separate pyDevSup as a module from IOC

### ISSUE THREAD

**Issue by iljabek** [mdavidsaver/pyDevSup#9]
Hello,

I'm testing following design:
```
/opt/epics
          /modules
                  /[...]
                  /pyDevSup
                           /devsupApp
                           /mysupApp
                                     /fitting_sup.py
                                     /fitting_sup.db
                           /python3.5/linux-x86_64/fitting_sup.py
          /iocs
                  /iocmy
                           /myApp
                                  /fitting.py
                                  /fitting.db
                           /python3.5/linux-x86_64/fitting.py
```
* once with the mysupApp inside the pyDevSup (which works fine)
* and once with the myApp separate from pyDevSup, linking to its binary
* the last one is giving me the following error
```
MY:PV: Exception in add_record
Traceback (most recent call last):
  File "/opt/epics/modules/pyDevSup/python3.5/linux-x86_64/devsup/db.py", line 338, in processLink
    mod = importmod(modname)
  File "/opt/epics/modules/pyDevSup/python3.5/linux-x86_64/devsup/util.py", line 18, in importmod
    return __import__(modname, fromlist=['__should_not_exist'])
ImportError: No module named 'fitting'
```

I guess it tries to look for modules in `/opt/epics/modules/pyDevSup/python3.5/linux-x86_64/`and does not know about `/opt/epics/iocs/iocmy/python3.5/linux-x86_64/`

does this error interpretation make sense? is this desired behaviour?

**Comment by mdavidsaver** [comment]
External modules need to set `$TOP` (and optionally `$ARCH`) in their environment prior to `iocInit()` to include `$TOP/python$PY_VER/$ARCH` in `$PYTHONPATH`.  A simple way to do this is by sourcing 'envPaths'.

http://mdavidsaver.github.io/pyDevSup/environment.html#pythonpath

https://github.com/mdavidsaver/pyDevSup/blob/44e5bd98b9bf2516585da6fcd844a68d36a3311c/devsupApp/src/setup.c#L339-L360

**Comment by iljabek** [comment]
I think I have given the correct values for `$TOP` and `$ARCH` in 'iocmy'. the error does not change.

at the time of execution of `/opt/epics/iocs/iocBoot/iocmy/st.cmd` the binary (in my case) `/opt/epics/modules/pyDevSup/bin/linux-x86_64/softIocPy3.5` is already compiled and is being called.
it will not contain the specific python path.

sofar what works for me is to call the `st.cmd` with `export PYTHONPATH=${PYTONPATH}:$$PWD/python$(PY_VER)/$(EPICS_HOST_ARCH); st.cmd ...`

I'm sorry, I don't understand how to tell python in run-time where to look for includes. could you expand?

**Comment by mdavidsaver** [comment]
> sofar what works for me is ...

This looks very nearly the same as what the code I quoted above is doing if your st.cmd script contains:

```
epicsEnvSet("TOP", "$PWD")
```

This is only a convince though.  You may find it more convenient/clear to explicitly setting `$PYTHONPATH` before lanching softIocPy, or extending `sys.path` within.  All the usual ways of defining the python module search path should work as normal.

After starting softIocPy you can inspect the search path with:

```
py "import sys"
py "print(sys.path)"
```

This often helps me to get an idea of what settings have actually been applied.

**Comment by mdavidsaver** [comment]
Were you able to resolve this issue and set the python path?
